[project]
name = "botza"
version = "0.1.0"
description = "A modern Telegram Bot framework for Python."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "CyberHuginn" }
]

dependencies = [
    "httpx>=0.28"
]

[dependency-groups]
dev = [
    "ruff>=0.6.0",
    "pytest>=8.0",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["botza*"]
exclude = [
    "tests*",
    "examples*",
    "docs*",
    "assets*",
]